import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('empty journal and isolated motorcycle, trip, fuel, and expense records', async ({ page, context }) => {
  async function openTripTab(name: string) {
    const link = page.getByRole('navigation', { name: 'Trip sections' }).getByRole('link', { name, exact: true })
    await link.click()
    await expect(link).toHaveAttribute('aria-current', 'page')
  }
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('No trips recorded yet.')).toBeVisible()
  await expect(page.getByText('0 km').first()).toBeVisible()
  await page.screenshot({ path: 'test-results/dashboard-empty-desktop.png', fullPage: true })

  await page.goto('/garage')
  await page.getByLabel('Manufacturer').fill('Honda')
  await page.getByLabel('Model', { exact: true }).fill('CB350')
  await page.getByLabel('Nickname').fill('Alpha')
  await page.getByLabel('Current odometer km').fill('10000')
  await page.getByRole('button', { name: 'Add motorcycle' }).click()
  await expect(page.getByRole('heading', { name: 'Alpha' })).toBeVisible()
  await page.getByLabel('Manufacturer').fill('Royal Enfield')
  await page.getByLabel('Model', { exact: true }).fill('Himalayan')
  await page.getByLabel('Nickname').fill('Bravo')
  await page.getByLabel('Current odometer km').fill('4000')
  await page.getByRole('button', { name: 'Add motorcycle' }).click()
  await expect(page.getByRole('heading', { name: 'Bravo' })).toBeVisible()

  async function createTrip(title: string, origin: string, destination: string, motorcycle: string) {
    await page.goto('/trips/new')
    await page.getByLabel('Trip name').fill(title)
    await page.getByLabel('Start location').fill(origin)
    await page.getByLabel('Destination', { exact: true }).fill(destination)
    await page.getByLabel('Motorcycle').selectOption({ label: motorcycle })
    await page.getByRole('button', { name: 'Create trip' }).click()
    await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
    return new URL(page.url()).pathname.split('/').at(-1)!
  }

  const a = await createTrip('Trip A', 'Chennai', 'Pondicherry', 'Alpha')
  const b = await createTrip('Trip B', 'Bengaluru', 'Mysuru', 'Bravo')
  const c = await createTrip('Trip C', 'Kochi', 'Munnar', 'Alpha')
  expect(new Set([a, b, c]).size).toBe(3)
  for (const [id, title] of [[c, 'Trip C'], [a, 'Trip A'], [b, 'Trip B'], [c, 'Trip C'], [b, 'Trip B'], [a, 'Trip A']]) {
    await page.goto(`/trips/${id}`)
    await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
  }

  await page.goto(`/trips/${b}/edit`)
  await page.getByLabel('Trip name').fill('Trip B edited')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('heading', { name: 'Trip B edited', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Trip B edited', exact: true })).toBeVisible()
  await page.goto(`/trips/${a}`)
  await expect(page.getByRole('heading', { name: 'Trip A', exact: true })).toBeVisible()

  await page.goto('/garage')
  await page.getByRole('button', { name: 'Set active' }).click()
  await page.goto(`/trips/${a}`)
  await expect(page.getByText('Alpha', { exact: true })).toBeVisible()

  await page.goto('/garage')
  const alphaDossier = await page.locator('article').filter({ has: page.getByRole('heading', { name: 'Alpha' }) }).getByRole('link', { name: 'Open dossier' }).getAttribute('href')
  const bravoDossier = await page.locator('article').filter({ has: page.getByRole('heading', { name: 'Bravo' }) }).getByRole('link', { name: 'Open dossier' }).getAttribute('href')
  await page.goto(alphaDossier!)
  await page.getByLabel('Service type').fill('Lubrication')
  await page.getByLabel('Component').fill('Chain')
  await page.getByLabel('Odometer km').fill('10050')
  await page.getByRole('button', { name: 'Log service' }).click()
  await expect(page.getByText('Chain - Lubrication')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Chain - Lubrication')).toBeVisible()
  await page.goto('/garage')
  await expect(page.locator('article').filter({ has: page.getByRole('heading', { name: 'Alpha' }) })).toContainText('10,050 km')
  await page.goto(bravoDossier!)
  await expect(page.getByText('Chain - Lubrication')).toHaveCount(0)

  await page.goto('/fuel')
  await page.getByLabel('Motorcycle').selectOption({ label: 'Alpha' })
  await page.getByLabel('Odometer km').fill('10000')
  await page.getByLabel('Litres').fill('10')
  await page.getByRole('button', { name: 'Log fuel' }).click()
  await expect(page.getByRole('button', { name: 'Edit fuel fill at 10,000 km' })).toBeVisible()
  await page.getByLabel('Odometer km').fill('10320')
  await page.getByLabel('Litres').fill('10.2')
  await page.getByRole('button', { name: 'Log fuel' }).click()
  await expect(page.getByText('31.4 km/L').first()).toBeVisible()
  await page.getByRole('button', { name: 'Edit fuel fill at 10,320 km' }).click()
  await page.getByLabel('Litres').fill('20')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByText('16.0 km/L').first()).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete fuel fill at 10,320 km' }).click()
  await expect(page.getByText('Not enough data').first()).toBeVisible()

  await page.goto('/expenses')
  await page.getByLabel('Amount').fill('420')
  await page.getByLabel('Trip').selectOption({ label: 'Trip B edited' })
  await page.getByRole('button', { name: 'Add expense' }).click()
  await expect(page.getByRole('button', { name: 'Edit food expense' })).toBeVisible()
  await page.goto(`/trips/${b}`)
  await openTripTab('Expenses')
  await expect(page.getByText('INR 420', { exact: true }).first()).toBeVisible()
  await page.goto(`/trips/${a}`)
  await openTripTab('Expenses')
  await expect(page.getByText('INR 420', { exact: true })).toHaveCount(0)
  await openTripTab('Overview')

  await page.route('**/nominatim.openstreetmap.org/reverse**', async (route) => route.fulfill({ json: { display_name: 'Recorded checkpoint' } }))
  await context.grantPermissions(['geolocation'], { origin: 'http://127.0.0.1:5173' })
  await context.setGeolocation({ latitude: 12.9716, longitude: 77.5946 })
  await page.getByRole('button', { name: 'Start trip' }).click()
  await expect(page.getByText('Active', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'Log fuel' })).toHaveAttribute('href', /\?tab=fuel$/)
  await expect(page.getByRole('link', { name: 'Add expense' })).toHaveAttribute('href', /\?tab=expenses$/)
  await expect(page.getByRole('link', { name: 'Add photo' })).toHaveAttribute('href', /\?tab=photos$/)
  await page.getByRole('button', { name: 'Record location' }).click()
  await expect(page.getByText('REACHED: Recorded checkpoint')).toBeVisible()
  await context.setGeolocation({ latitude: 12.9816, longitude: 77.6046 })
  await page.getByRole('button', { name: 'Record location' }).click()
  await page.getByRole('button', { name: 'Add event' }).click()
  await page.getByLabel('Event title').fill('Bridge crossing')
  await page.getByLabel('Notes').fill('Traffic was light')
  await page.getByRole('button', { name: 'Save event' }).click()
  await openTripTab('Journal')
  await expect(page.getByText('Trip started', { exact: true })).toBeVisible()
  await expect(page.getByText('Reached here', { exact: true })).toHaveCount(2)
  const bridgeEvent = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Bridge crossing' }) })
  await expect(bridgeEvent).toContainText('Recorded checkpoint')
  await expect(bridgeEvent).toContainText('Traffic was light')
  await openTripTab('Overview')
  await page.route('**/api.open-meteo.com/v1/forecast**', async (route) => route.fulfill({ json: { current: { temperature_2m: 28, precipitation: 3, wind_speed_10m: 12, relative_humidity_2m: 88, weather_code: 63 } } }))
  await page.getByRole('button', { name: 'Weather', exact: true }).click()
  await openTripTab('Weather')
  await expect(page.getByText(/Rain \| 28 C/)).toBeVisible()
  await expect(page.getByText(/Not enough paired GPS and weather records/)).toBeVisible()
  await openTripTab('Readiness')
  await page.getByLabel('Tyres', { exact: true }).check()
  await expect(page.getByLabel('Tyres', { exact: true })).toBeChecked()
  await expect(page.getByText('Checklist saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Tyres', { exact: true })).toBeChecked()
  await openTripTab('Overview')
  await page.getByRole('button', { name: 'End trip' }).click()
  await expect(page.getByText('GPS distance').locator('..').locator('dd')).not.toHaveText('0 km')
  await openTripTab('Journal')
  await expect(page.getByText('Trip completed', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/trip-detail-desktop.png', fullPage: true })
  await page.getByRole('link', { name: 'Replay' }).first().click()
  await expect(page.getByRole('heading', { name: 'Route Replay' })).toBeVisible()
  await expect(page.getByText('Trip started', { exact: true })).toBeVisible()
  const replaySlider = page.getByRole('slider', { name: 'Timeline position' })
  await replaySlider.fill((await replaySlider.getAttribute('max')) ?? '0')
  await expect(page.getByText('Bridge crossing', { exact: true })).toBeVisible()
  await expect(page.getByText(/Recorded checkpoint/).last()).toBeVisible()
  await page.screenshot({ path: 'test-results/replay-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Play replay' }).click()
  await expect(page.getByRole('slider', { name: 'Timeline position' })).toBeVisible()
  await page.goto(`/trips/${a}`)
  await openTripTab('Photos')
  await page.locator('input[type="file"]').setInputFiles({ name: 'ride.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l7sAAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByAltText('Trip photo')).toBeVisible()
  await page.getByLabel('Linked event').selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Place on map' }).click()
  await expect(page.getByRole('heading', { name: 'Place photo on map' })).toBeVisible()
  await page.locator('.leaflet-container').click({ position: { x: 120, y: 120 } })
  await expect(page.getByRole('button', { name: 'Save location' })).toBeEnabled()
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.getByText(/Location: manual placement/)).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe(`myride-trip-${a}.json`)
  const exported = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(exported.trip.id).toBe(a)
  expect(exported.photos).toHaveLength(1)
  expect(exported.photos[0].locationSource).toBe('manual')
  expect(exported.photos[0].latitude).toEqual(expect.any(Number))
  expect(exported.photos[0].rideEventId).toEqual(expect.any(String))
  expect(exported.expenses).toHaveLength(0)

  await page.getByRole('link', { name: 'Trips', exact: true }).first().click()
  await page.getByRole('link', { name: 'Create trip', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Record a New Journey' })).toBeVisible()
  await context.setOffline(true)
  await page.getByLabel('Trip name').fill('Offline Trip')
  await page.getByLabel('Start location').fill('Offline origin')
  await page.getByLabel('Destination', { exact: true }).fill('Offline destination')
  await page.getByLabel('Motorcycle').selectOption({ label: 'Alpha' })
  await page.getByRole('button', { name: 'Create trip' }).click()
  await expect(page.getByRole('heading', { name: 'Offline Trip' })).toBeVisible()
  await page.getByRole('button', { name: 'Start trip' }).click()
  await page.getByRole('button', { name: 'Record location' }).click()
  await openTripTab('Journal')
  await expect(page.getByText('Reached here', { exact: true })).toHaveCount(1)
  await openTripTab('Photos')
  await page.locator('input[type="file"]').setInputFiles({ name: 'offline-ride.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l7sAAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByAltText('Trip photo')).toBeVisible()
  await openTripTab('Fuel')
  await page.getByLabel('Odometer km').fill('10400')
  await page.getByLabel('Litres').fill('8')
  await page.getByRole('button', { name: 'Log fuel' }).click()
  await expect(page.getByText('8.0 L at 10,400 km')).toBeVisible()
  await page.getByRole('button', { name: 'Edit fuel fill at 10,400 km' }).click()
  await page.getByLabel('Litres').fill('9')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByText('9.0 L at 10,400 km')).toBeVisible()
  await openTripTab('Expenses')
  await page.getByLabel('Amount').fill('125')
  await page.getByRole('button', { name: 'Add expense' }).click()
  await expect(page.getByText('INR 125', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Edit food expense' }).click()
  await page.getByLabel('Amount').fill('130')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByText('INR 130', { exact: true }).first()).toBeVisible()
  await context.setOffline(false)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Offline Trip' })).toBeVisible()
  await openTripTab('Journal')
  await expect(page.getByText('Reached here', { exact: true })).toHaveCount(1)
  await openTripTab('Photos')
  await expect(page.getByAltText('Trip photo')).toBeVisible()
  await openTripTab('Fuel')
  await expect(page.getByText('9.0 L at 10,400 km')).toBeVisible()
  await openTripTab('Expenses')
  await expect(page.getByText('INR 130', { exact: true }).first()).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete food expense' }).click()
  await expect(page.getByText('No expenses recorded for this trip.')).toBeVisible()

  await page.goto('/profile')
  await page.getByLabel('Name', { exact: true }).first().fill('Rider One')
  await page.getByLabel('Home base').fill('Bengaluru')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByText('Profile saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Name', { exact: true }).first()).toHaveValue('Rider One')
  await expect(page.getByLabel('Home base')).toHaveValue('Bengaluru')

  for (const viewport of [{ name: 'tablet', width: 768, height: 1024 }, { name: 'mobile', width: 390, height: 844 }, { name: 'small-mobile', width: 320, height: 700 }]) {
    await page.setViewportSize(viewport)
    for (const [name, path] of [['trip-detail', `/trips/${a}`], ['replay', `/trips/${a}/replay`], ['motorcycle-detail', alphaDossier!]]) {
      await page.goto(path)
      await expect(page.locator('h1')).toBeVisible()
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
      expect(overflow, `${name} overflows at ${viewport.width}px`).toBe(false)
      await page.screenshot({ path: `test-results/${name}-${viewport.name}.png`, fullPage: true })
    }
  }
  await page.setViewportSize({ width: 1440, height: 900 })

  await page.goto(`/trips/${b}`)
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page).toHaveURL(/\/trips$/)
  await page.goto(`/trips/${b}`)
  await expect(page.getByText('TRIP COULD NOT BE LOADED')).toBeVisible()
  await page.goto(`/trips/${a}`)
  await expect(page.getByRole('heading', { name: 'Trip A', exact: true })).toBeVisible()
  await page.goto('/expenses')
  await expect(page.getByText('No trip').last()).toBeVisible()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'MyRide', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
  expect(overflow).toBe(false)
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true })
  expect(pageErrors).toEqual([])
})
