import { expect, test } from '@playwright/test'

test('opt-in maintenance reminder reflects proven service due state', async ({ page }) => {
  await page.goto('/garage')
  await page.getByLabel('Manufacturer').fill('Honda')
  await page.getByLabel('Model', { exact: true }).fill('CB350')
  await page.getByLabel('Nickname').fill('Reminder bike')
  await page.getByLabel('Current odometer km').fill('1200')
  await page.getByLabel('Service interval km').fill('1000')
  await page.getByRole('button', { name: 'Add motorcycle' }).click()
  await page.getByRole('link', { name: 'Open dossier' }).click()
  await page.getByLabel('Service type').fill('General service')
  await page.getByLabel('Component').fill('Engine oil')
  await page.getByLabel('Odometer km').fill('0')
  await page.getByRole('button', { name: 'Log service' }).click()
  await expect(page.getByText('Engine oil - General service')).toBeVisible()

  await page.goto('/')
  await expect(page.getByText('Maintenance due', { exact: true })).toHaveCount(0)
  await page.goto('/settings')
  await page.getByLabel('Maintenance reminders').check()
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByText('Settings saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Maintenance reminders')).toBeChecked()
  await page.goto('/')
  await expect(page.getByRole('status').filter({ hasText: 'Maintenance due' })).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Reminder bike' })).toBeVisible()

  await page.goto('/settings')
  await page.getByLabel('Maintenance reminders').uncheck()
  await page.getByRole('button', { name: 'Save settings' }).click()
  await page.goto('/')
  await expect(page.getByText('Maintenance due', { exact: true })).toHaveCount(0)
})
